FROM almalinux:9
ENV COURSE="Docker" \
    DURATION="120 Hours" \
ARG TRAINER="Nagendra"
RUN echo "Hi, Course is: ${COURSE}, Duration is ${DURATION} and the Trainer is ${TRAINER}"
CMD ["sleep", "1000"]